PACKAGE = sound-scripts
VERSION := 0.62.1

SH = alsa.config alsa.utils

RPMOPT = --clean --rmsource --rmspec

.PHONY: log changelog

all: check

check:
	@for i in $(SH);do /bin/bash -n $$i || exit 1;echo $$i syntax OK;done

install:
	mkdir -p $(DESTDIR)/usr/share/alsa
	mkdir -p $(DESTDIR)/usr/{s,}bin
	mkdir -p $(DESTDIR)/etc/sysconfig/
	mkdir -p $(DESTDIR)/etc/sound/profiles/alsa/
	mkdir -p $(DESTDIR)/etc/sound/profiles/pulse/
	mkdir -p $(DESTDIR)/lib/udev/rules.d/
	mkdir -p $(DESTDIR)/etc/modprobe.d/
	install -m 644 alsa.rules $(DESTDIR)/lib/udev/rules.d/
	install -m 755 alsa.dev $(DESTDIR)/usr/sbin/alsa.agent
	install -D -m755 alsa_default.pl $(DESTDIR)/etc/rc.d/rc.alsa_default
	install -D -m644 alsa.config $(DESTDIR)/etc/sysconfig/alsa
	install -D -m644 alsa.utils $(DESTDIR)/usr/share/alsa/alsa-utils
	install -D -m755 reset_sound $(DESTDIR)/usr/bin/reset_sound
	install -D -m644 snd-oss.conf.modprobe $(DESTDIR)/etc/sound/profiles/alsa/snd-oss.conf
	ln -s ../../etc/sound/profiles/alsa/snd-oss.conf $(DESTDIR)/etc/modprobe.d/snd-oss.conf
	install -D -m644 pulse-snd-oss.conf $(DESTDIR)/etc/sound/profiles/pulse/snd-oss.conf

clean:
	rm -f *~ core .#*[0-9] core.* *.bak

# rules to build a test rpm

cleandist:
	rm -rf $(PACKAGE)-$(VERSION) $(PACKAGE)-$(VERSION).tar.xz

# rules to build a distributable rpm

dist:
	git archive --prefix=$(PACKAGE)-$(VERSION)/ HEAD | xz -cv -T0 > $(PACKAGE)-$(VERSION).tar.xz;

export:

log: changelog

changelog: ../common/username
	svn2cl --accum --authors ../common/username.xml
	rm -f ChangeLog.bak
	svn commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog
